config/routes.rb
Rails.application.routes.draw do
  get 'installation', to: 'installations#new', as: :new_installation_path
  resource :installation, only: [:new, :create]
  resources :password_resets, except: [:destroy]

  get 'login' => 'users/sessions#new', as: :login
  delete 'logout' => 'users/sessions#destroy', as: :logout

  namespace :users do
    resources :sessions
    resource :registration
    resource :password
  end

  resources :links
  resources :groups

  get ':slug', to: 'links#visit', as: :visit_link
  root to: 'dashboard#show'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login
  layout 'simple'

  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user
      @user.deliver_reset_password_instructions!
      redirect_to(login_path, notice: 'Instruções foram enviadas para o seu e-mail')
    else
      flash.now[:alert] = 'Reset password failed'
      render :new, status: 422
    end
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    not_authenticated if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.change_password!(params[:user][:password])
      redirect_to(login_path, notice: 'Senha foi atualizada com sucesso.')
    else
      flash.now[:alert] = 'Edit password failed'
      render :edit, status: 422
    end
  end
end

app/views/password_resets/edit.html.erb
<div class="col-lg-5 center">
  <h1><%= t('.title') %></h1>

  <%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
    <%= render 'shared/errors', object: @user %>

    <div class="form-group">
      <%= f.label :email %><br />
      <%= @user.email %>
    </div>
    <div class="form-group">
      <%= f.label :password %><br />
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit t('buttons.send'), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="col-lg-5 center">
  <h1><%= t('.title') %></h1>

  <%= form_tag password_resets_path, method: :post do  %>
  <div class="form-group">
    <%= label_tag :email %><br />
    <%= text_field_tag :email, nil, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= submit_tag t('buttons.reset_password'), class: 'btn btn-primary' %>
  </div>
<% end %>
</div>