config/routes.rb
Rails.application.routes.draw do
  get 'installation', to: 'installations#new', as: :new_installation_path
  resource :installation, only: [:new, :create]
  resources :password_resets, except: [:destroy]

  get 'login' => 'users/sessions#new', as: :login
  delete 'logout' => 'users/sessions#destroy', as: :logout

  namespace :users do
    resources :sessions
    resource :registration
    resource :password
  end

  resources :links
  resources :groups

  get ':slug', to: 'links#visit', as: :visit_link
  root to: 'dashboard#show'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :links, dependent: :destroy

  validates :name, presence: true

  def self.sorted
    order('lower(name) ASC')
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.sorted
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new, status: 422
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit, status: 422
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <%= render 'shared/errors', object: group %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-success' %>
    <% if group.persisted? %>
      <%= link_to t('delete_link'), @group, method: :delete, data: { confirm: 'Tem certeze?' }, class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="col-lg-5">
  <%= link_to t('back_link'), groups_path %>

  <p class="label label-default">grupos</p>

  <h1><%= t('.title') %></h1>

  <%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<%= link_to t('back_link'), root_path %>

<h1><%= t('.title') %> <%= link_to t('add_group_link'), new_group_path, class: 'btn btn-primary pull-right' %></h1>

<table class="table">
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td><%= t('created_at_column') %> <%= l group.created_at, format: :long %></td>
        <td><%= t('.links_count', count: group.links_count) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<div class="col-lg-5">
  <%= link_to t('back_link'), groups_path %>

  <h1><%= t('.title') %></h1>

  <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<%= link_to t('back_link'), groups_path %>

<p class="label label-default">grupos</p>

<h1><%= @group.name %> <%= link_to t('edit_link'), edit_group_path(@group), class: 'btn btn-primary pull-right' %></h1>

<%= render 'links/links', links: @group.links.most_visited %>