config/routes.rb
Rails.application.routes.draw do
  get 'installation', to: 'installations#new', as: :new_installation_path
  resource :installation, only: [:new, :create]
  resources :password_resets, except: [:destroy]

  get 'login' => 'users/sessions#new', as: :login
  delete 'logout' => 'users/sessions#destroy', as: :logout

  namespace :users do
    resources :sessions
    resource :registration
    resource :password
  end

  resources :links
  resources :groups

  get ':slug', to: 'links#visit', as: :visit_link
  root to: 'dashboard#show'
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :visits, dependent: :destroy
  belongs_to :group, counter_cache: true

  validates :name, presence: true
  validates :original_url, presence: true
  validates :slug, presence: true, uniqueness: true
  accepts_nested_attributes_for :group, reject_if: :should_create_group?

  after_initialize :generate_slug

  def generate_slug
    return if slug.present?

    self.slug = random_string
  end

  def random_string(size = 8)
    chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    Array.new(size) { chars[rand(chars.size)] }.join
  end

  def should_create_group?
    group_id?
  end

  def self.most_visited(limit = nil)
    collection = order('visits_count DESC')
    collection = collection.limit(limit) if limit
    collection
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  skip_before_action :require_login, only: [:visit]
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.most_visited
  end

  def show
    @start_period = Time.zone.today.last_month
    @end_period = Time.zone.today

    @start_period = params[:start_period].to_date if params[:start_period]
    @end_period = params[:end_period].to_date if params[:end_period]

    @visits = @link.visits.where('created_at BETWEEN ? AND ?', @start_period, @end_period)
  end

  def visit
    @link = Link.find_by!(slug: params[:slug])
    @visit = @link.visits.build(
      ip: request.remote_ip,
      referer: request.referer,
      user_agent: request.user_agent
    )
    @visit.save!

    GenerateVisitMetadataJob.perform_later(@visit.id)

    redirect_to @link.original_url, status: 301
  end

  def new
    @link = Link.new(new_link_params)
  end

  def edit
  end

  def create
    @link = Link.new(new_link_params)

    if @link.save
      redirect_to @link, notice: 'Link was successfully created.'
    else
      render :new, status: 422
    end
  end

  def update
    if @link.update(edit_link_params)
      redirect_to @link, notice: 'Link was successfully updated.'
    else
      render :edit, status: 422
    end
  end

  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def new_link_params
    params
      .require(:link).permit(:name, :original_url, :slug, :group_id, group_attributes: [:name])
  end

  def edit_link_params
    params.require(:link).permit(:name, :group_id, group_attributes: [:name])
  end
end

app/views/links/_form.html.erb
<%= form_for(link) do |f| %>
  <%= render 'shared/errors', object: link %>

  <div class="form-group">
    <%= f.label :original_url %>
    <%= f.text_field :original_url, disabled: link.persisted?, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :slug %>
    <%= f.text_field :slug, disabled: link.persisted?, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <div>
      <%= f.label :group_id, 'Escolha um grupo' %>
      <%= f.select :group_id, options_from_collection_for_select(Group.sorted, :id, :name), include_blank: true %>
    </div>
    <div>
      <%= f.fields_for :group_attributes do |ff| %>
        <%= ff.label :name, 'Ou crie um novo' %>
        <%= ff.text_field :name, class: 'form-control' %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-success' %>
    <% if link.persisted? %>
      <%= link_to t('delete_link'), @link, method: :delete, data: { confirm: 'Tem certeze?' }, class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
<% end %>

<script>
  $('#link_group_id').on('change', function() {
    if (this.value === 'new_group') {
      $('#link_new_group').parent().removeClass('hide');
    } else {
      $('#link_new_group').parent().addClass('hide');
    }
  });
</script>

app/views/links/_links.html.erb
<table class="table table-bordered">
  <tbody>
    <% links.each do |link| %>
      <tr>
        <td><%= link_to link.name || link.original_url, link %></td>
        <% if defined?(show_group) && show_group %>
          <td>em <%= link_to link.group.name, link.group %></td>
        <% end %>
        <td><%= link_to visit_link_url(link.slug), visit_link_url(link.slug), target: '_blank' %></td>
        <td><%= t('.visits_count', count: link.visits_count) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/links/_stats.html.erb
<table class="table">
  <% stats.each do |stat| %>
    <tr>
      <td><%= stat[0] %></td>
      <td><%= number_to_human stat[1] %></td>
      <td><%= number_to_percentage stat[2], precision: 0 %></td>
    </tr>
  <% end %>
</table>

app/views/links/edit.html.erb
<div class="col-lg-5">
  <h1><%= t('.title') %></h1>

  <%= render 'form', link: @link %>

  <%= link_to t('show_link'), @link %> |
  <%= link_to t('back_link'), links_path %>
</div>

app/views/links/index.html.erb
<h1 class="page-header">Links</h1>
<p class="lead">Get the lowdown on the key pieces of Bootstrap's infrastructure, including our approach to better, faster, stronger web development.</p>

<%= render 'links', links: @links %>

<%= link_to 'Novo link', new_link_path, class: 'btn btn-primary' %>

app/views/links/new.html.erb
<div class="col-lg-5">
  <h1><%= t('.title') %></h1>

  <%= render 'form', link: @link %>

  <%= link_to t('back_link'), links_path %>
</div>

app/views/links/show.html.erb
<%= link_to t('back_link'), links_path %>
<h1><%= @link.name %> (<%= t('links.links.visits_count', count: @link.visits_count) %>) <%= link_to t('edit_link'), edit_link_path(@link), class: 'btn btn-primary pull-right' %></h1>

<div style="width: 185px; padding: 30px 0;">
  <input type="text" name="daterange" class="form-control">
</div>

<p>
  <strong>Grupo:</strong>
  <%= @link.group.name %>
</p>

<p>
  <strong>URL original:</strong>
  <%= @link.original_url %>
</p>

<p>
  <strong>URL encurtada:</strong>
  <%= visit_link_url(@link.slug) %>
</p>

<p>
  <strong>Criado em:</strong>
  <%= l(@link.created_at, format: :long) %>
</p>

<p>
  <strong>Visitas no período:</strong>
  <%= @visits.count %>
</p>

<%= area_chart @visits.group_by_day(:created_at).count %>

<div class="row">
  <div class="col-md-6">
    <h2>Origem</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <%= render 'stats', stats: stats_table(@visits.group(:source).count) %>
  </div>

  <div class="col-md-6">
    <h2>Localização</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>

    <%= render 'stats', stats: stats_table(@visits.group(:location).count) %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h2>Navegador</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <%= render 'stats', stats: stats_table(@visits.group(:browser).count) %>
  </div>

  <div class="col-md-6">
    <h2>Platform</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <%= render 'stats', stats: stats_table(@visits.group(:platform).count) %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('input[name="daterange"]').daterangepicker({
      locale: {
        format: 'DD/MM/YYYY',
        cancelLabel: 'Clear'
      },
      dateLimit: {
        'months': 1
      },
      startDate: "<%= l(@start_period, format: '%d/%m/%Y') %>",
      endDate: "<%= l(@end_period, format: '%d/%m/%Y') %>",
      maxDate: "<%= l(Time.zone.today, format: '%d/%m/%Y') %>"
    });

    $('input[name="daterange"]').on('apply.daterangepicker', function(ev, picker) {
      var startDate = picker.startDate.format('DD/MM/YYYY');
      var endDate = picker.endDate.format('DD/MM/YYYY');
      var url = "<%= link_path @link %>" + '?start_period=' + startDate + '&end_period=' + endDate;
      window.location.href = url;
    });

    $('input[name="daterange"]').on('cancel.daterangepicker', function(ev, picker) {
      $(this).val('');
      window.location.href = "<%= link_path @link %>";
    });
  });
</script>