config/routes.rb
Rails.application.routes.draw do
  get 'installation', to: 'installations#new', as: :new_installation_path
  resource :installation, only: [:new, :create]
  resources :password_resets, except: [:destroy]

  get 'login' => 'users/sessions#new', as: :login
  delete 'logout' => 'users/sessions#destroy', as: :logout

  namespace :users do
    resources :sessions
    resource :registration
    resource :password
  end

  resources :links
  resources :groups

  get ':slug', to: 'links#visit', as: :visit_link
  root to: 'dashboard#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Encurtador</title>
        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application" %>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>

        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<%= root_path %>" class="navbar-brand">CNL Encurtador</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="<%= root_path %>">Dashboard</a>
                        </li>
                        <li>
                            <a href="<%= groups_path %>">Groups</a>
                        </li>
                    </ul>

                    <form class="navbar-form navbar-left" method="GET" action="<%= new_link_url %>">
                      <div class="form-group">
                        <input type="text" name="link[original_url]" class="form-control" placeholder="Informe url">
                      </div>
                      <button type="submit" class="btn btn-default">Encurtar</button>
                    </form>

                    <% if current_user %>

                    <ul class="nav navbar-nav navbar-right">
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                          <%= image_tag gravatar_image_url(current_user.email), width: 20 %>
                          <%= current_user.name %>
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li><a href="<%= edit_users_registration_path %>">Editar perfil</a></li>
                          <li role="separator" class="divider"></li>
                          <li><%= link_to "Logout", :logout, method: :delete %></li>
                        </ul>
                      </li>
                    </ul>
                    <% else %>
                      <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to 'Login', login_path %></li>
                      </ul>
                    <% end %>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <p id="notice"><%= flash[:notice] %></p>
                <p id="alert"><%= flash[:alert] %></p>
                <%= yield %>
            </div>
        </div>
    </body>
</html>

app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Encurtador</title>
        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application" %>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <p id="notice"><%= flash[:notice] %></p>
                <p id="alert"><%= flash[:alert] %></p>
                <%= yield %>
            </div>
        </div>
    </body>
</html>